---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-customer
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-customer
        image: public.ecr.aws/nautible/nautible-app-ms-customer:352d542c3a83cf71955e7b493561aacdf2011201
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
